# Homebrew formula for systimus-proxy. Generated by
# .github/workflows/proxy-release.yml on every `proxy-v*` tag.
# Do not hand-edit in the tap repo — edit the renderer in the systimus repo.
class SystimusProxy < Formula
  desc "Local HTTPS passthrough for Claude Code that captures exact AI spend"
  homepage "https://systimus.io"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/systimus/proxy-releases/releases/download/v0.3.0/systimus-proxy-0.3.0-darwin-arm64.tar.gz"
      sha256 "9c8baa266de0dff842c4493241a682012ba884dd36b2279143f9a3f902e97f21"
    end
    on_intel do
      url "https://github.com/systimus/proxy-releases/releases/download/v0.3.0/systimus-proxy-0.3.0-darwin-amd64.tar.gz"
      sha256 "3348dcc2ebb4c48c83937b0a3c9d05c4dd8a431967f46ced91e504d72dc76911"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/systimus/proxy-releases/releases/download/v0.3.0/systimus-proxy-0.3.0-linux-arm64.tar.gz"
      sha256 "0b01e46413a57ec7b615af255330dcfc3f73e1d2518aca7ea835fa3b1b320b56"
    end
    on_intel do
      url "https://github.com/systimus/proxy-releases/releases/download/v0.3.0/systimus-proxy-0.3.0-linux-amd64.tar.gz"
      sha256 "beaa67b3b0427e0768625d4d7e46c1f097c3453aaeb697bf2a9e320bbc759977"
    end
  end

  def install
    bin.install "systimus-proxy"
  end

  # Managed background service: `brew services start systimus-proxy`.
  # The binary reads its API key from ~/.systimus/proxy/config.toml (written by
  # `systimus-proxy setup`), so the generated plist carries NO secrets and no
  # user-specific paths — the binary resolves its own config at runtime.
  service do
    run [opt_bin/"systimus-proxy"]
    keep_alive crashed: true
    log_path var/"log/systimus-proxy.log"
    error_log_path var/"log/systimus-proxy-error.log"
    working_dir HOMEBREW_PREFIX
  end

  def caveats
    <<~EOS
      First-time setup (writes your API key and wires your shell, once):
        systimus-proxy setup

      Run it as a managed background service (restarts on crash, starts on login):
        brew services start systimus-proxy

      `setup` offers to add this to your shell profile; to wire it by hand:
        eval "$(systimus-proxy shellenv)"      # fish: systimus-proxy shellenv | source

      Run `systimus-proxy setup` before starting the service — without a config
      file the proxy exits on launch and the service won't stay up. Diagnostics:
        tail -f #{HOMEBREW_PREFIX}/var/log/systimus-proxy-error.log

      `brew uninstall` leaves your config and spooled events in place. To remove
      them (flushes any pending spend events first):
        systimus-proxy purge
    EOS
  end

  test do
    assert_match(/\d+\.\d+\.\d+|dev/, shell_output("#{bin}/systimus-proxy --version"))
  end
end
