# Homebrew formula for systimus-proxy. Generated by
# .github/workflows/proxy-release.yml on every `proxy-v*` tag.
# Do not hand-edit in the tap repo — edit the renderer in the systimus repo.
class SystimusProxy < Formula
  desc "Local HTTPS passthrough for Claude Code that captures exact AI spend"
  homepage "https://systimus.io"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/systimus/proxy-releases/releases/download/v0.4.0/systimus-proxy-0.4.0-darwin-arm64.tar.gz"
      sha256 "b54ad8200587d6019033734c56ab1862dc7e1edfd889743f53ce9b3296c283fc"
    end
    on_intel do
      url "https://github.com/systimus/proxy-releases/releases/download/v0.4.0/systimus-proxy-0.4.0-darwin-amd64.tar.gz"
      sha256 "04329b700015bb7a3065f61504a2f3837ac3ca098d9c8e2fdb154f2449fc0383"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/systimus/proxy-releases/releases/download/v0.4.0/systimus-proxy-0.4.0-linux-arm64.tar.gz"
      sha256 "1189f1d28fbd92434d4076d96cdad58e4ce6d9ebcbf20e74480fae79b52e7bab"
    end
    on_intel do
      url "https://github.com/systimus/proxy-releases/releases/download/v0.4.0/systimus-proxy-0.4.0-linux-amd64.tar.gz"
      sha256 "b8a675a7854baf41d4056c765a087b58f26047819802b7e843ecb65f0b3d3f48"
    end
  end

  def install
    bin.install "systimus-proxy"
  end

  # Managed background service: `brew services start systimus-proxy`.
  # The binary reads its API key from ~/.systimus/proxy/config.toml (written by
  # `systimus-proxy setup`), so the generated plist carries NO secrets and no
  # user-specific paths — the binary resolves its own config at runtime.
  service do
    run [opt_bin/"systimus-proxy"]
    keep_alive crashed: true
    log_path var/"log/systimus-proxy.log"
    error_log_path var/"log/systimus-proxy-error.log"
    working_dir HOMEBREW_PREFIX
  end

  def caveats
    <<~EOS
      First-time setup (writes your API key and wires your shell, once):
        systimus-proxy setup

      Run it as a managed background service (restarts on crash, starts on login):
        brew services start systimus-proxy

      `setup` offers to add this to your shell profile; to wire it by hand:
        eval "$(systimus-proxy shellenv)"      # fish: systimus-proxy shellenv | source

      Run `systimus-proxy setup` before starting the service — without a config
      file the proxy exits on launch and the service won't stay up. Diagnostics:
        tail -f #{HOMEBREW_PREFIX}/var/log/systimus-proxy-error.log

      `brew uninstall` leaves your config and spooled events in place. To remove
      them (flushes any pending spend events first):
        systimus-proxy purge
    EOS
  end

  test do
    assert_match(/\d+\.\d+\.\d+|dev/, shell_output("#{bin}/systimus-proxy --version"))
  end
end
